syncing changes

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -2,11 +2,12 @@ name: ESLint
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["**"]
   pull_request:
-    branches: [ "main" ]
+    branches: ["**"]
   schedule:
-    - cron: '17 23 * * 4'  # every Thursday at 11:17 PM UTC
+    - cron: "17 23 * * 4"
+  workflow_dispatch:
 
 jobs:
   eslint:
@@ -27,18 +28,19 @@ jobs:
           npm install @microsoft/eslint-formatter-sarif@3.1.0
 
       - name: Run ESLint and generate SARIF
+        id: lint
         env:
           SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
         run: |
-          npx eslint . \
-            --config .eslintrc.js \
-            --ext .js,.jsx,.ts,.tsx \
+          npx eslint . --config eslint.config.mjs \
             --format @microsoft/eslint-formatter-sarif \
-            --output-file eslint-results.sarif
-        continue-on-error: false
+            --output-file eslint-results.sarif || echo "eslint_failed=true" >> $GITHUB_OUTPUT
 
-      - name: Upload analysis results to GitHub
+      - name: Upload SARIF file
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: eslint-results.sarif
-          wait-for-processing: true
+
+      - name: Fail if ESLint had errors
+        if: steps.lint.outputs.eslint_failed == 'true'
+        run: exit 1
