upload sarif file before sending failed test

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -25,15 +25,19 @@ jobs:
         run: npm ci
 
       - name: Run ESLint and generate SARIF
+        id: lint
         env:
           SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
         run: |
           npx eslint . --config eslint.config.mjs \
             --format @microsoft/eslint-formatter-sarif \
-            --output-file eslint-results.sarif
-        continue-on-error: false
+            --output-file eslint-results.sarif || echo "eslint_failed=true" >> $GITHUB_OUTPUT
 
       - name: Upload SARIF file
         uses: github/codeql-action/upload-sarif@v2
         with:
           sarif_file: eslint-results.sarif
+
+      - name: Fail if ESLint had errors
+        if: steps.lint.outputs.eslint_failed == 'true'
+        run: exit 1
